### ISSUE TITLE
Deprecate @music-metadata/s3

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata-s3#101]
Since I split of [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) from [@music-metadata/s3](https://github.com/Borewit/music-metadata-s3), only a few lines of code remained. 

What remains is a module demonstrating how to integrate [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) with [music-metadata](https://github.com/Borewit/music-metadata):

https://github.com/Borewit/music-metadata-s3/blob/58a0f7fde0879e7d63fe88215c53ee1ca4971cb4/lib/index.ts#L17-L20

[@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) essentially made this module obsolete. An advantage of using [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) directly, is that is not tightly coupled with music-metadata.

I also created [an issue](https://github.com/Borewit/tokenizer-s3/issues/63) to investigate to investigate a more loose coupling between [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) &  [aws-sdk-js](https://github.com/aws/aws-sdk-js).

I think **it is time to deprecate [@music-metadata/s3](https://github.com/Borewit/music-metadata-s3)**.

> How do I migrate from [@music-metadata/s3](https://github.com/Borewit/music-metadata-s3) to [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3)?

_Example:  [Reading audio metadata from Amazon S3](https://github.com/Borewit/tokenizer-s3#reading-audio-metadata-from-amazon-s3)_

**Comment by Borewit** [comment]
@ffxsam, can you please depend on [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) directly and provide feedback?

**Comment by ffxsam** [comment]
@Borewit Hey! It'll be a while before I'll have time to look at this, but thanks for the update.

But regarding the S3 metadata code example:

```js
const s3tokenizer = require("@tokenizer/s3");
const mm = require("music-metadata/lib/core");
/**
 * Retrieve metadata from Amazon S3 object
 * @param objRequest S3 object request
 * @param options music-metadata options
 * @return Metadata
 */
async function parseS3Object(s3, objRequest, options) {
    const s3Tokenizer = await  s3tokenizer.makeTokenizer(s3, objRequest, options);
    return mm.parseFromTokenizer(s3Tokenizer, options);
}

(async () => {
  const s3 = new S3();
  
  const metadata = await mmS3client.parseS3Object({
        Bucket: 'music-metadata',
        Key: 'Various Artists - 2008 - netBloc Vol 13 (color in a world of monochrome) {BSCOMP0013} [MP3-V0]/01 - Nils Hoffmann - Sweet Man Like Me.mp3'
      }
    );
})();
```

Where is `mmS3client` coming from? Seems like something is missing. Also, `parseS3Object` is defined as a standalone function, yet it's used as a method to this client that isn't instantiated anywhere.

**Comment by Borewit** [comment]
> Where is mmS3client coming from? Seems like something is missing. Also, parseS3Object is defined as a standalone function, yet it's used as a method to this client that isn't instantiated anywhere.

Thanks for pointing that out @ffxsam, I fixed the example: https://github.com/Borewit/tokenizer-s3/commit/d4a62d2230a4a2ef9f9f7f078ebd8b2aaa024e42.

**Comment by ffxsam** [comment]
Awesome, thanks! I won't have time to dive into this for several weeks, but I've bookmarked it to come back later.

**Comment by Borewit** [comment]
Last release: [v0.6.1](https://www.npmjs.com/package/@music-metadata/s3/v/0.6.1)

Marked as deprecated in [NPM](https://www.npmjs.com/package/@music-metadata/s3): _"Obsolete, use [@tokenizer/s3](https://github.com/Borewit/tokenizer-s3) instead."_

**Comment by Borewit** [comment]
Will make repo read-only
