### ISSUE TITLE
disableChunked option is required - intentional?

### ISSUE THREAD

**Issue by ffxsam** [Borewit/music-metadata-s3#7]
Not sure if this is intentional, but the `disableChunked` option is required. It seems like maybe it should be optional, and default to `false`.

**Comment by Borewit** [comment]
Thanks for letting me know.

**Comment by Borewit** [comment]
Maybe you are not using the latest release?

Added a unit test with default options:

https://github.com/Borewit/music-metadata-s3/blob/bcec0d5c91812c9f52d8f273953b312ab1c2fda3/test/test.js#L31-L38

**Comment by ffxsam** [comment]
Just to clarify:

Options are optional 😄  But if I specify some other option, e.g. `skipCovers: true`, TypeScript yells at me because `disableChunked` is not optional in this case.

**Comment by Borewit** [comment]
Overlooked that one, fixed in [v0.3.2](https://www.npmjs.com/package/@music-metadata/s3/v/0.3.2)
